# Generated by Django 4.1 on 2022-08-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=798)),
                ('mail', models.EmailField(max_length=254)),
                ('product', models.CharField(max_length=78)),
            ],
        ),
    ]
